# Nombre del servidor 
servidor.nombre=DESKTOP-6BSLFEE\SQLEXPRESS
# Usuario para la conexi\uFFFDn
servidor.usuario =sa
# Password para la conexi\uFFFDn
servidor.password=milagros123
# Puerto de Conexi\uFFFDn
servidor.port=1433
# Nombre Base datos
<<<<<<< HEAD
bd.name=TaqueriaBD2
=======
bd.name=TaqueriaBD
>>>>>>> 92ab6fd6b55d0fed6b54a7c5bb8011a6927316bc
# Controlador de SqlServer
servidor.control=jdbc:sqlserver
# Ip Servidor
ip=localhost